<link rel="stylesheet" type="text/css" href="public/assets/css/bootstrap.min.css" >
<link rel="stylesheet" type="text/css" href="public/assets/css/sb-admin.css">
<div class="jumbotron">
	<h1>JRESTPad</h1>
	<p>Sem login, apenas uma URL</p>
	<p>O texto é salvo automaticamente</p>
	<p>Edite online com seus amigos</p>
	<p>
		Aplicação baseada no <a href="http://www.dontpad.com" target="_blank">Dontpad</a>
	</p>
</div>

<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">Digite sua URL</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-lg-6">
						<div class="form-group">
							<input class="form-control" placeholder="URL" id="url">
						</div>
				</div> <!-- /.col-lg-6 (nested) -->
				<div class="col-lg-6">
						<div class="form-group">
							<button id="enviar" type="submit" class="btn btn-default">Enviar</button>
						</div>
					
				</div> <!-- /.col-lg-6 (nested) -->
			</div> <!-- /.row (nested) -->
			
		</div><!-- /.panel-body -->
		<div class="panel-footer"></div>	
	</div> <!-- /.panel -->
</div>
<script type="text/javascript" src="public/assets/js/jquery-1.11.1.js"></script>
<script type="text/javascript" src="public/assets/js/new_main.js"></script>