<div class="row">
    <!--<div class="col-lg-6">-->
    <form role="form">
        <div class="form-group">
            <div class="panel panel-default ()">
                <div class="panel-heading">
                    <h3 class="panel-title">O conteúdo será exibido abaixo</h3>
                </div>
                <div class="panel-body" id="resultado">

                </div>    
                <div class="panel-footer">Panel footer</div>
            </div>
        </div>
        <div class="form-group">
            <input id="conteudo" required class="form-control" placeholder="Digite seu texto e tecle Enter">
        </div>
        <button type="submit" id="enviar" class="btn btn-default">Submit Button</button>

    </form>
    <!--</div>-->
    <!-- /.col-lg-6 (nested) -->
</div>
<!-- /.row (nested) -->
</div>