<div id="noConnectionAlert" class="hide">Nenhuma conexão localizada.
	Novas tentativas a cada 2 segundos.</div>
<div id="menu-div">
	<ul id="menu">
	</ul>
</div>

<div id="text-div" align="center">
	<textarea id="text"></textarea>
</div>
<input type="hidden" name="lastUpdate" id="lastUpdate" value="" />

<script type="text/javascript" src="public/assets/js/jquery-1.11.1.js"></script>
<script type="text/javascript" src="public/assets/js/request.js"></script>